const types = {
  FETCH_SELECTED_POST_REQUEST: 'FETCH_SELECTED_POST_REQUEST',
  FETCH_SELECTED_POST_SUCCESS: 'FETCH_SELECTED_POST_SUCCESS',
  FETCH_SELECTED_POST_FAILURE:  'FETCH_SELECTED_POST_FAILURE',
};

export default types;
